In [1]:
# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
#IMPORTING THE DATASET
dataset = pd.read_csv('cropmonth_rain.csv')

In [3]:
dataset

CROP NAME    CROP TYPE  MONTH_AVG  MIN TEMP(°C )  \
0              BARLEY (JOW)           RABI      11.00             12   
1           MAIZE (KHARIF)          Kharif       6.00             25   
2             MAIZE (RABI)            Rabi      10.50             21   
3                      OATS           RABI      10.00             20   
4                     RICE           Rabi       11.00             16   
5       WHEAT (KANAK/GEHU)            Rabi      11.00             21   
6                  COTTON           Kharif       4.50             15   
7      BAJRA NAPIER HYBRID          Kharif       5.50             30   
8                 BERSEEM            RABI       10.50             15   
9            FINGER MILLET         KHARIF        6.00             20   
10                    GUAR          Kharif       8.50             28   
11            GUINEA GRASS            Rabi       2.50             19   
12                LUCERNE             Rabi      10.50             15   
13            SENJI HYBRID            Rabi      11.50             25   
14                 SHAFTAL            RABI      10.00             12   
15                TEOSINTE          KHARIF       4.50             21   
16                 COWPEA           Kharif       5.25             22   
17               DHAINCHA      KHARIF-RABI       6.00             22   
18                   MESTA          Kharif       5.50             25   
19                 SUNHEMP            Rabi       3.00             20   
20               GROUNDNUT         KHARIF        5.00             20   
21            LINSEED/ FLAX          Rabi       10.50             21   
22                 MUSTARD            Rabi      10.50             22   
23               SAFFLOWER           Rabi       10.50             15   
24                 SOYBEAN          Kharif       6.50             18   
25               SUNFLOWER         KHARIF        3.50             20   
26   BENGAL GRAM(CHICKPEA)         KHARIF        8.50             24   
27       GREEN GRAM(MOONG)          Kharif       3.50             25   
28     KIDNEY BEAN (RAJMA)            RABI      10.50             15   
29               MASH (URD)         Kharif       3.50             15   
..                        ...          ...        ...            ...   
69                  STEVIA            Rabi       2.50             25   
70              SWEET FLAG           RABI       11.00             10   
71                  TULSI           KHARIF       4.50             14   
72              CORIANDER            Rabi       10.50             15   
73                  FENNEL            Rabi      10.50             15   
74               FENUGREEK     Rabi-Kharif       3.50             15   
75          GINGER (ADRAKH)         Kharif       5.75             12   
76        TURMERIC (HALDI)          Kharif       5.50             24   
77             ARUM (ARVI)          KHARIF       5.00             18   
78               ASH GOURD            Rabi       2.50             15   
79                 BRINJAL           Rabi       10.50             15   
80                CAPSICUM            RABI      10.00             21   
81                  CARROT            Rabi       9.50              7   
82             CAULIFLOWER           RABI       11.00             12   
83                  CELERY            Rabi       9.50             12   
84                 CHILLY             Rabi      10.50             18   
85                CUCUMBER          KHARIF       6.50             25   
86                  GARLIC            Rabi       9.50             10   
87     KHARIF ONION (PYAZ)          Kharif       5.50             21   
88                 LETTUCE          Kharif      10.25             20   
89                    OKRA          Kharif       6.50             20   
90                    PEAS           Rabi       10.75             15   
91                  POTATO            Rabi       9.50             14   
92       RABI ONION (PYAZ)            Rabi      10.50       

In [4]:
X = dataset.iloc[: , 2:].values

In [5]:
X

array([[1.1000e+01, 1.2000e+01, 3.2000e+01, 9.5000e+02],
       [6.0000e+00, 2.5000e+01, 3.0000e+01, 7.5000e+02],
       [1.0500e+01, 2.1000e+01, 2.7000e+01, 7.5000e+02],
       [1.0000e+01, 2.0000e+01, 3.0000e+01, 9.0000e+01],
       [1.1000e+01, 1.6000e+01, 3.0000e+01, 1.5000e+03],
       [1.1000e+01, 2.1000e+01, 2.6000e+01, 7.5000e+02],
       [4.5000e+00, 1.5000e+01, 3.5000e+01, 7.7500e+02],
       [5.5000e+00, 3.0000e+01, 3.0000e+01, 4.5000e+02],
       [1.0500e+01, 1.5000e+01, 2.7000e+01, 6.5000e+02],
       [6.0000e+00, 2.0000e+01, 3.4000e+01, 1.0000e+03],
       [8.5000e+00, 2.8000e+01, 3.2000e+01, 1.0500e+02],
       [2.5000e+00, 1.9000e+01, 2.3000e+01, 1.0500e+03],
       [1.0500e+01, 1.5000e+01, 3.2000e+01, 3.2500e+02],
       [1.1500e+01, 2.5000e+01, 3.2000e+01, 4.5000e+02],
       [1.0000e+01, 1.2000e+01, 2.0000e+01, 5.0000e+02],
       [4.5000e+00, 2.1000e+01, 3.2000e+01, 6.2500e+02],
       [5.2500e+00, 2.2000e+01, 3.5000e+01, 9.2500e+02],
       [6.0000e+00, 2.2000e+01,

In [6]:
Y = dataset.iloc[: , 0].values

In [7]:
Y

array([' BARLEY (JOW)  ', ' MAIZE (KHARIF)   ', ' MAIZE (RABI)   ',
       ' OATS  ', ' RICE   ', ' WHEAT (KANAK/GEHU)   ', ' COTTON    ',
       ' BAJRA NAPIER HYBRID   ', ' BERSEEM    ', ' FINGER MILLET   ',
       ' GUAR   ', ' GUINEA GRASS   ', ' LUCERNE    ', ' SENJI HYBRID   ',
       ' SHAFTAL   ', ' TEOSINTE   ', ' COWPEA    ', ' DHAINCHA    ',
       ' MESTA   ', ' SUNHEMP   ', ' GROUNDNUT   ', ' LINSEED/ FLAX  ',
       ' MUSTARD   ', ' SAFFLOWER   ', ' SOYBEAN   ', ' SUNFLOWER   ',
       ' BENGAL GRAM(CHICKPEA)   ', ' GREEN GRAM(MOONG)   ',
       ' KIDNEY BEAN (RAJMA)   ', ' MASH (URD)  ', ' PIGEON PEA (TUR)   ',
       ' RICEBEAN   ', ' SUGARCANE    ', ' LEMON    ',
       ' LIME (NIMBOO)   ', ' CHRYSANTHEMUM   ', ' GERBERA   ',
       ' MARIGOLD   ', ' ROSE   ', ' DREK   ', ' EUCALYPTUS   ',
       ' POPLAR   ', ' SAGWAN   ', ' GUAVA   ', ' KINNOW  ',
       ' MULBERRY    ', ' MUSKMELON   ', ' ORANGE/ MANDARINS (SANTRA)   ',
       ' PEAR (NASHPATI)   ', ' PLUM   ', ' SW

In [8]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X)

In [9]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
classifier.fit(X_train, Y)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=5, p=2,
           weights='uniform')

In [42]:
x_test = [[5 , 28.5 , 40.6, 3.4]]
                             
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_test = sc.fit_transform(x_test)

In [52]:
predicted_index = classifier.kneighbors(X_test, n_neighbors=8)[1]

In [53]:
predicted_index

array([[89, 43,  9, 94, 26, 36, 39, 88]])

In [58]:
predicted_index[0]

array([89, 43,  9, 94, 26, 36, 39, 88])

In [65]:
predicted_index_month = []

for i in predicted_index[0]:
    predicted_index_month.append(X[i][0])

In [66]:
predicted_index_month

[6.5, 9.0, 6.0, 9.5, 8.5, 9.5, 8.5, 10.25]

In [67]:
diff_month = []

for i in predicted_index_month :
    diff = i - x_test[0][0]
    diff_month.append(diff)
    diff = 0

In [68]:
diff_month

[1.5, 4.0, 1.0, 4.5, 3.5, 4.5, 3.5, 5.25]

In [72]:
indx_sorted = np.argsort(diff_month)
indx_sorted

array([2, 0, 4, 6, 1, 3, 5, 7])

In [73]:
final_predicted_month = []

for i in indx_sorted :
    final_predicted_month.append(predicted_index[0][i])

In [79]:
final_predicted_month = final_predicted_month[0:5]

final_predicted_month

[9, 89, 26, 39, 43]

In [80]:
top_5_crops = []

for i in final_predicted_month:
    top_5_crops.append(Y[i])

In [81]:
top_5_crops

[' FINGER MILLET   ',
 ' OKRA   ',
 ' BENGAL GRAM(CHICKPEA)   ',
 ' DREK   ',
 ' GUAVA   ']

In [82]:
X[9 , :]

array([   6.,   20.,   34., 1000.])

In [83]:
X[89, :]

array([   6.5,   20. ,   30. , 1000. ])

In [85]:
X[26, :]

array([  8.5,  24. ,  30. , 750. ])

In [86]:
X[39, :]

array([  8.5,  23. ,  35. , 800. ])

In [87]:
X[43, :]

array([   9.,   15.,   30., 1000.])

In [88]:
import pickle

In [89]:
filename = 'knn_model.sav'
pickle.dump(classifier, open(filename, 'wb'))

In [91]:
loaded_model = pickle.load(open(filename, 'rb'))